---
Name: app
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'simple'
    - '$default'
SilverStripe\i18n\i18n:
  default_locale: 'en_NZ'
